[package]
name = "aloroid/cubecat"
description = "A plugin framework designed to allow for interconnecting with other plugins"
license = "MIT"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"