[package]
name = "aloroid/cubecat"
description = "A plugin framework designed to allow for interconnecting with other plugins"
exclude = ["Packages"]
license = "MIT"
version = "0.3.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Signal = "sleitnick/signal@1.4.2"